class CommConst:
    # train_path = '/home/why/source/models/research/object_detection/images/train'
    train_path = '/home/why/dataset/train'
    test_path = '/home/why/source/models/research/object_detection/images/test'
    # data_path = '/home/why/source/models/research/object_detection/data'
    data_path = '/home/why/dataset/generate'
    # train_csv = '/home/why/source/models/research/object_detection/data/train.csv'
    train_csv = '/home/why/dataset/generate/train_csv'
    test_csv = '/home/why/source/models/research/object_detection/data/test.csv'
    record_path = '/home/why/dataset/generate/train.record'
    model_path = '/home/why/dataset/result/saved_model/saved_model.pb'
    # label_map_path = '/home/why/source/models/research/object_detection/data/game_label_map.pbtxt'
    label_map_path = '/home/why/dataset/generate/game_label_map.pbtxt'
