BASE_DIR = "/home/tommy/work/python/pas/script/ty/images/"
BOX = BASE_DIR + "box.png"
SURE = BASE_DIR + "sure.png"
CLOSE1 = BASE_DIR + "close1.png"
CLOSE2 = BASE_DIR + "close2.png"
CLOSE3 = BASE_DIR + "close3.png"
